<?php

namespace Fossil\Tests;

/**
 * Test class for Dispatcher.
 * Generated by PHPUnit on 2011-12-16 at 23:27:24.
 */
class DispatcherTest extends FossilTestCase {
    /**
     * @var Fossil\Dispatcher
     */
    protected $object;
    
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = self::$container->get("Dispatcher");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    /**
     * @todo Implement testRunRequest().
     */
    public function testRunRequest() {
        // First, test that run is called
        $runStub = $this->getMockBuilder('Fossil\Requests\BaseRequest')->disableOriginalConstructor()->getMock();
        $runStub->expects($this->once())
                ->method('run');
        
        $this->object->runRequest($runStub, false);
    }
    
    public function testRunRequest404Exception() {
        $exception = new \Fossil\Exceptions\NoSuchControllerException("Test");
        
        $exceptStub = $this->getMockBuilder('Fossil\Requests\BaseRequest')->disableOriginalConstructor()->getMock();
        $exceptStub->expects($this->any())
                ->method('run')
                ->will($this->throwException($exception));
        
        $resp = $this->object->runRequest($exceptStub, false);
        
        $this->assertEquals("fossil:error/404", $resp->getTemplateName());
    }
    
    public function testRunRequestDBException() {
        $exception = new \PDOException("Test");
        
        $exceptStub = $this->getMockBuilder('Fossil\Requests\BaseRequest')->disableOriginalConstructor()->getMock();
        $exceptStub->expects($this->any())
                ->method('run')
                ->will($this->throwException($exception));
        
        $resp = $this->object->runRequest($exceptStub, false);
        
        $this->assertEquals("fossil:error/db", $resp->getTemplateName());
        
    }

    public function testRunRequestGenericException() {
        $exception = new \Exception("Test");
        
        $exceptStub = $this->getMockBuilder('Fossil\Requests\BaseRequest')->disableOriginalConstructor()->getMock();
        $exceptStub->expects($this->any())
                ->method('run')
                ->will($this->throwException($exception));
        
        $resp = $this->object->runRequest($exceptStub, false);
        
        $this->assertEquals("fossil:error/generic", $resp->getTemplateName());
    }
    
    public function testRunRequestLogsException() {
        $exception = new \Exception("Test");
        
        $exceptStub = $this->getMockBuilder('Fossil\Requests\BaseRequest')->disableOriginalConstructor()->getMock();
        $exceptStub->expects($this->any())
                ->method('run')
                ->will($this->throwException($exception));
        
        $resp = $this->object->runRequest($exceptStub, false);
        
        // Grab the error logger and check that the exception is there
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
    
    /**
     * @todo Implement testGetTopRequest().
     */
    public function testGetTopRequest() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetCurrentRequest().
     */
    public function testGetCurrentRequest() {
        $obj = $this->object;
        // Use a closure to return the current request during the call
        $gcrCB = function() use($obj) {
            return $obj->getCurrentRequest();
        };
        $runStub = $this->getMockBuilder('Fossil\Requests\BaseRequest')->disableOriginalConstructor()->getMock();
        $runStub->expects($this->any())
                ->method('run')
                ->will($this->returnCallback($gcrCB));
        
        $result = $this->object->runRequest($runStub, false);
        
        $this->assertEquals($runStub, $result);
    }

}

?>
